version: "3.7"
services:
  redis:
    container_name: redis_stack
    image: redis/redis-stack-server:latest # aws do not supports https://repost.aws/questions/QUQyrs0KQCQwuILrT_S1VInQ/redisstack-for-redissearch-functionality-on-elasticache-memorydb-or-otherwise
    ports:
      - "6379:6379"

  postgres:
    container_name: postgres_stack
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
