version: "3.7"
services:
  redis:
    container_name: redis_stack
    hostname: redis
    image: redis/redis-stack-server:latest # aws do not supports https://repost.aws/questions/QUQyrs0KQCQwuILrT_S1VInQ/redisstack-for-redissearch-functionality-on-elasticache-memorydb-or-otherwise
    ports:
      - "6379:6379"

  mariadb:
    container_name: mariadb_stack
    image: mariadb:10
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=experts_gpt
    volumes:
      - ./mariadb_data:/var/lib/mysql/
#  app:
#    image: expert_gpts
#    container_name: app
#    build:
#        context: .
#        dockerfile: Dockerfile
#    ports:
#      - "8000:8000"
#    command: ["tail", "-f", '/dev/null']
#    volumes:
#      - ./:/app
#      - ./huggingface_hub:/root/.cache/huggingface/hub/
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [gpu]
